import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DefaultLayouts from "../features/partials/DefaultLayouts";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          width: "100dvw",
          display: 'flex',
          height: "100dvh",
          justifyContent: "center",
          alignItems: "center",
          backgroundColor: "white",
        }}
      >
        <DefaultLayouts>{children}</DefaultLayouts>
      </body>
    </html>
  );
}
